language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

install:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction

script:
    - ./vendor/bin/phpunit
